### ISSUE TITLE
exporterparser/jaeger: unknown field 'CollectorEndpoint'.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#127]
In https://github.com/census-instrumentation/opencensus-service/pull/124 we've added the Jaeger Exporter to Agent. However, when compiling with the Jaeger exporter we got a error:
```bash
exporter/exporterparser/jaeger.go:58:3: unknown field 'CollectorEndpoint' in struct literal of type "go.opencensus.io/exporter/jaeger".Options
```

Maybe we should include a dedicated version for Jaeger in go.mod and go.sum.

**Comment by songy23** [comment]
Thanks @moderation for reporting this bug.

**Comment by songy23** [comment]
cc @odeke-em 

Here's a screenshot of this error, running on my Linux workstation:
`go get github.com/census-instrumentation/opencensus-service/cmd/ocagent`

![screenshot from 2018-10-23 14-30-32](https://user-images.githubusercontent.com/10536136/47392058-4db43f00-d6d0-11e8-96c3-6504306174d3.png)

**Comment by odeke-em** [comment]
Thanks @songy23 and @moderation for the report!

You just need to update your local versions of `go.opencensus.io` because that field was added a month ago in https://github.com/census-instrumentation/opencensus-go/commit/3d73a6ce623ed9ea81d474461e9aea31c78b483b This isn't a bug but a case of a stale dependency
```shell
go get -u -v go.opencensus.io/exporter/...
```
should cut the deal for you.

**Comment by moderation** [comment]
@odeke-em that works. Thanks.

**Comment by songy23** [comment]
Verified, worked for me as well, thanks!

**Comment by odeke-em** [comment]
@moderation 
>@odeke-em that works. Thanks. Is there a way to automatically update this dependency? Or should this be a documentation update?

Great question: so basically:
a) you can either stick to using dependency management e.g. `go mod download`
b) `go get -u -v github.com/census-instrumentation/cmd/ocagent`

I'd prefer b) because not everyone has the new dependency management with `go mod` in Go1.11 but also this repository is in development so there might be lapses in updating those `go.mod` and `go.sum` files.

I don't think this needs a documentation update  as we've got https://github.com/census-instrumentation/opencensus-service#usage which makes using the go tool automatic without `go get -u` but for the reasons I've mentioned above it would be counterproductive to have dependency management but also encourage `go get -u` and then expect everyone to use Go1.11 too.
