### ISSUE TITLE
discussion: rename interceptors to importers?

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-service#151]
It seems like importers could have been named as "importers". I had to look for documentation to understand what an interceptor is, although "importer" would be more self descriptive. Importer is also symmetric to an exporter.

What do you think?

**Comment by songy23** [comment]
I guess we copied the name "interceptor" from gRPC (e.g [intercetpor.go](https://github.com/grpc/grpc-go/blob/4f70de23e6d83e800fe1b15bdd6e3e11b9a1f27a/interceptor.go)). I proposed "adapter" initially though I don't have strong opinions towards this. "importer" sounds good to me too.

/cc @bogdandrutu @odeke-em

**Comment by odeke-em** [comment]
@rakyll thank you for the request for clarification and the suggestion!

IMHO interceptor is used because it implies a sort of box-in-the-middle to capture then reroute input which is the intention here -- both passive and active capturing for example the Zipkin "interceptor" is just an HTTP server that receives spans sent to it.
Importer suggests an active fetch model where we seek out configurations/sources and pull from them which misses the part about the component passively waiting/being a sink. My opinion is to keep the package name as is.

However, I'll defer to others for the final decision on renaming.

/cc also @pjanotti @flands @maynk

**Comment by flands** [comment]
Another vote for importer here.

**Comment by pjanotti** [comment]
"Receiver" or "Listener" fit the actual role pretty well, and as mentioned this fits with the "passive" way that they act, instead of an active role implied by "importer" or "interceptor".

**Comment by yurishkuro** [comment]
+1 for receiver.

**Comment by flands** [comment]
Looks like "receiver" wins. Will open an issue.

**Comment by flands** [comment]
Tracked via #166

**Comment by bogdandrutu** [comment]
+1 for "receiver".
