### ISSUE TITLE
Agent trace pipe: is transforming data to 1st to OC proto, then to SpanData, then exporters work

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#167]
At first I don't see a reason why the data needs to be transformed to OC proto (see zipkin receiver). We can save one hop for any interceptor by removing the OC proto step and going straight to SpanData.

**Comment by odeke-em** [comment]
Great question @pjanotti! The reason why we are transforming them into OC Proto I believe is because the agent-core might do some processing on the Spans and the collector which y'all building will need spans to be in the same format regardless of source e.g. OpenCensus libraries, Zipkin, Jaeger etc, currently because the middle pipeline hasn't yet built we are going directly to exporting.

/cc @bogdandrutu @songy23

**Comment by pjanotti** [comment]
I see. Anyway, we should accomplish any core transformation with a single hop to either to "Span Proto with Node" or `SpanData`, in the end should be: receiver -> OC core format -> exporters.

**Comment by bogdandrutu** [comment]
The opencensus-go exporters work with SpanData (equivalent with Proto) because we don't want a dependency on proto in the core library. @odeke-em did the change in order to reuse the exporters to transform proto + node into SpanData. This decision can be revisited.

**Comment by pjanotti** [comment]
I see, so actually this can be done in the future if we think it is worth: instead of directly re-using the existing exporters in opencensus-service we can create "service-exporters" that consume OC-proto directly. Ok, closing this.
