### ISSUE TITLE
receiver/jaeger: add Jaeger Agent running on UDP

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#206]
As discussed via code review with @pjanotti, it'd be nice to have the Jaeger agent's behavior also in the Jaeger receiver.

Let's also ensure that these addresses are supported(if applicable), as per https://www.jaegertracing.io/docs/1.7/deployment/#agent

Port | Protocol | Function
-- | -- | --
5775 | UDP | accept zipkin.thrift over compact thrift protocol
6831 | UDP | accept jaeger.thrift over compact thrift protocol
6832 | UDP | accept jaeger.thrift over binary thrift protocol
5778 | HTTP | serve configs, sampling strategies

**Comment by odeke-em** [comment]
Kindly paging @yurishkuro to ask if we should support all those agent endpoints or instead just support 6831?

**Comment by yurishkuro** [comment]
Maybe we could find another way to avoid reimplementing jaeger-agent functionality?

To answer the exact question, you don't need 5775 zipkin.thrift port imo, as it's been a long time since we switch Jaeger clients not to use zipkin data format. None of the current oss versions of Jaeger clients use it, only some legacy versions.

**Comment by flands** [comment]
https://github.com/open-telemetry/opentelemetry-service/issues/128
