### ISSUE TITLE
Received service names are not preserved by the collector when exporting

### ISSUE THREAD

**Issue by JonasKunz** [census-instrumentation/opencensus-service#551]
It seems like the OpenCensus Collector does not preserve the "service names" of incoming spans.
When using the Jaeger exporter on the collector, the service name shown in Jaeger is either the default ("OpenCensus") or the one configured via the "service_name" option of the Jaeger exporter.

The desired behaviour is that the collector preserves the service names of received spans, as the collector should be designed to receive spans from multiple services with different names.

I tried the following two scenarios:
* Java OC-Trace Exporter sending to the OC Collector, which then exports to Jaeger
* Java Jaeger Exporter sending to the OC Collector, which then exports to Jaeger

In both cases I configured the Java exporters with a custom service name, which was then lost in the OC collector. The OC-service version is 0.1.6.

I guess this issue is somehow related to https://github.com/census-instrumentation/opencensus-specs/issues/74, as this would most likely automatically solve this issue.

**Comment by pjanotti** [comment]
Hi @JonasKunz, sorry for the delay. Are you using the Jaeger exporter via the `exporters:` section in the config?

Currently the exporters configured via `exporters:` section typically drop the service name because the leverage straight the client lib exporters (iirc zipkin and oc exporter should handle it correctly). However, this should work with the collector by using `queued-exporters` in your configuration, example [here](https://github.com/census-instrumentation/opencensus-service/blob/afc7348f5624ae3f5ccd7e8739dec11d0fd2b926/demos/trace/oc-collector-config.yaml#L9). I understand that this is confusing situation and it is the backlog to be fixed, there are upcoming changes to config and unification between agent and collector that will address this issue. Please, give it a try using `queued-exporters:` to Jaeger and let's know how it goes.

**Comment by JonasKunz** [comment]
Thanks for your answer @pjanotti this indeed was the problem! I did not know the difference between `queued-exporters` and `exporters`. I tested it with the following scenarios, now the service names are preserved as expected:
Java Jaeger Exporter -> OC Collector -> Jaeger
Java OC Exporter -> OC Collector -> Jaeger
Java OC Exporter -> OC Agent w. OC Exporter -> OC Collector -> Jaeger

**Comment by pjanotti** [comment]
Thanks for testing the variations above @JonasKunz!

**Comment by JonasVerhofste** [comment]
@pjanotti It makes sense to preserve the service name of the original span, but that leaves me puzzled as to what the intended use of `service_name` of the exporters in the `exporters:` section is. Is it meant to be added as a tag somewhere in the future (i.e. "passed through" or something)?

**Comment by pjanotti** [comment]
Hi @JonasVerhofste, somehow I missed your comment earlier... the intention of `service_name` is to offer a way when using the receiver with the agent in scenario that it is picking up data from a single service (e.g.: side car). That said the recommendation is that this should be done at the application level, but it needs to be correctly preserved by the pipeline. There is no future plan usage for `service_name`.

If one wants to add attributes (aka: tags) the global attributes feature can be used instead, see https://github.com/census-instrumentation/opencensus-service#-global-attributes.

**Comment by drubin** [comment]
I just ran into this issue. I tried converting my `exporters:` to `queued-exporters:` but it seems only `jeager` and `zipkin` are supported?

Is there an easy way to get this functionality/workaround working with the other exporters. `datadog` / `honeycomb`?
