### ISSUE TITLE
interceptor/test: investigate the CI failure with TestOCInterceptor_endToEnd.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#95]
For example, in https://travis-ci.org/census-instrumentation/opencensus-service/builds/441996182?utm_source=github_status&utm_medium=notification:

```bash
=== RUN   TestOCInterceptor_endToEnd
--- FAIL: TestOCInterceptor_endToEnd (0.22s)
	opencensus_test.go:57: Failed to create the ocagent-exporter: Exporter.Start:: Failed to initiate the Config service: EOF
```

**Comment by songy23** [comment]
This looks like a flaky test. CI build succeeded in https://travis-ci.org/census-instrumentation/opencensus-service/builds/441996186?utm_source=github_status&utm_medium=notification with the exact same changes.

**Comment by odeke-em** [comment]
Flaky test in deed. I think that after https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/26 is merged and the vendored copy is updated, we should never have that flake. That is because the current version of the ocagent expects the config handshake first of which we haven't yet even implemented the Config service.

**Comment by songy23** [comment]
Maybe disable this test for the moment? This test failure has blocked several PRs.

**Comment by odeke-em** [comment]
Sounds like a plan!

**Comment by songy23** [comment]
Reopened this issue to track the debugging process on the test. We should re-enable this test once we made it stable.

**Comment by flands** [comment]
This will be addressed in the OpenTelemetry Service.
